error: provide better err message
Instead of a generic: compilation error with X, check logs.

Signed-off-by: Matthieu Baerts <matthieu.baerts@tessares.net>